# Generated by Django 5.2.8 on 2025-11-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Universidad_de_Buenos_Aires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultad', models.CharField(max_length=50)),
                ('carrera', models.CharField(max_length=50)),
            ],
        ),
    ]
