# Generated by Django 5.2.8 on 2025-11-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universidad_de_buenos_aires',
            name='image',
            field=models.ImageField(null=True, upload_to='imagenes_uba'),
        ),
        migrations.AlterField(
            model_name='universidad_de_buenos_aires',
            name='carrera',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='universidad_de_buenos_aires',
            name='facultad',
            field=models.CharField(max_length=100),
        ),
    ]
