# Generated by Django 5.2.8 on 2025-11-26 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_universidad_de_buenos_aires_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universidad_de_buenos_aires',
            old_name='image',
            new_name='imagen',
        ),
    ]
